### ISSUE TITLE
Missing exp and log functions

### ISSUE THREAD

**Issue by gpanders** [Calysto/calysto_scheme#33]
The `exp` and `log` functions are undefined:

```scheme
(exp 3)
Traceback (most recent call last):
  File "In [21]", line 1, col 2
RunTimeError: unbound variable 'exp'
```

```scheme
(log 10)
Traceback (most recent call last):
  File "In [21]", line 1, col 2
RunTimeError: unbound variable 'log'
```

**Comment by dsblank** [comment]
All of the extra functions, like math, are used from the Python packages. So your examples would be:

```scheme
(import "math")
(math.exp 3)
(math.log 10)
```
