### ISSUE TITLE
No such kernel named calysto_scheme

### ISSUE THREAD

**Issue by kramimus** [Calysto/calysto_scheme#6]
I just tried pip installing calysto in my local virtualenv and ipython/jupyter 5 cannot find the kernel:

```
$ python --version
Python 2.7.10
$ pip freeze | grep -E 'jupyter|ipython|calysto|metakernel'
calysto-scheme==1.2.0
ipython==5.1.0
ipython-genutils==0.1.0
jupyter==1.0.0
jupyter-client==4.3.0
jupyter-console==5.0.0
jupyter-core==4.1.0
metakernel==0.14.0
$ ipython console --kernel calysto_scheme
[TerminalIPythonApp] WARNING | Subcommand `ipython console` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter console` in the future
Traceback (most recent call last):
  File "/home/mark/.virtualenvs/web/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-109>", line 2, in initialize
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 300, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/IPython/core/application.py", line 446, in initialize
    self.parse_command_line(argv)
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 295, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/traitlets/config/application.py", line 488, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/IPython/core/application.py", line 236, in initialize_subcommand
    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/traitlets/config/application.py", line 426, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/jupyter_console/app.py", line 137, in initialize
    self.init_shell()
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/jupyter_console/app.py", line 105, in init_shell
    JupyterConsoleApp.initialize(self)
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/jupyter_client/consoleapp.py", line 334, in initialize
    self.init_kernel_manager()
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/jupyter_client/consoleapp.py", line 288, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/jupyter_client/manager.py", line 230, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/jupyter_client/manager.py", line 170, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/jupyter_client/manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/home/mark/.virtualenvs/web/local/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 175, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named calysto_scheme
```

`jupyter console --kernel calysto_scheme` gives similar results.

**Comment by dsblank** [comment]
There are two steps as the README.md says:

``` shell
pip3 install --upgrade calysto-scheme
python3 -m calysto_kernel install
```

**Comment by kramimus** [comment]
Yep, looks like I totally missed that, sorry!

I am able to load the kernel now, thanks!

**Comment by dsblank** [comment]
No problem! You are not the first :) Perhaps we need to say **two steps** up front in the doc.
